Repository cmpsc-481-s22-m1/GatorConfig, pull requests merged in 2022-01, with the labels that each got.

#16 Added support for commits.
  src/gator_yaml.py
  tests/test_gator_yaml.py
Labels: bug, enhancement

#17 Feature gui
  .github/workflows/main.yml
  .pylintrc
  poetry.lock
  pyproject.toml
  src/gui/check_file.py
  src/gui/form.py
  src/gui/homepage.py
  src/gui_main.py
  tests/test_gui_main.py
Labels: enhancement

#19 Feature path split
  src/gator_yaml.py
  src/split_file_path.py
Labels: enhancement

#23 Fixing GitHub Actions configuration
  src/actions_configuration.py
  tests/test_actions_configuration.py
Labels: bug

#22 Release/0.1.0
  .github/ISSUE_TEMPLATE/new-feature.md
  .github/cspell.json
  .github/workflows/main.yml
  .pylintrc
  README.md
  gatorconfig/__init__.py
  gatorconfig/actions_configuration.py
  gatorconfig/gator_config.py
  gatorconfig/gator_yaml.py
  gatorconfig/gui/check_file.py
  gatorconfig/gui/form.py
  gatorconfig/gui/homepage.py
  gatorconfig/gui_main.py
  gatorconfig/scrape_releases.py
  gatorconfig/split_file_path.py
  hello/say_hello.py
  poetry.lock
  pyproject.toml
  tests/test_actions_configuration.py
  tests/test_gator_config.py
  tests/test_gator_yaml.py
  tests/test_gui_main.py
  tests/test_say_hello.py
  tests/test_scrape_releases.py
  tests/test_split_file_path.py
Labels: enhancement
